using GitLabClone.Domain.Common;
using GitLabClone.Domain.Enums;

namespace GitLabClone.Domain.Entities;

public sealed class Issue : AuditableEntity, ISoftDeletable
{
    /// <summary>
    /// Project-scoped sequential issue number (like #1, #2, ...).
    /// Generated by the application layer, not the DB identity column.
    /// </summary>
    public int IssueNumber { get; set; }

    public string Title { get; set; } = string.Empty;
    public string? Description { get; set; }
    public IssueStatus Status { get; set; } = IssueStatus.Open;

    public Guid ProjectId { get; set; }
    public Project Project { get; set; } = null!;

    public Guid? AssigneeId { get; set; }
    public User? Assignee { get; set; }

    public Guid AuthorId { get; set; }
    public User Author { get; set; } = null!;

    // Soft delete
    public bool IsDeleted { get; set; }
    public DateTimeOffset? DeletedAt { get; set; }
    public string? DeletedBy { get; set; }

    // Navigation properties
    public ICollection<IssueComment> Comments { get; set; } = [];
    public ICollection<Label> Labels { get; set; } = [];
}
